### ISSUE TITLE
Init fails with an error "cannot find spin.toml"

### ISSUE THREAD

**Issue by mikkelhegn** [fermyon/spin-cloud-gpu#6]
```
> spin cloud-gpu init
Warning: You're using a pre-release version of Spin (1.6.0-pre0). This plugin might not be compatible (supported: >=1.4). Continuing anyway.
Deploying fermyon-cloud-gpu Spin app ...
Error: Failed to deploy fermyon-cloud-gpu: Warning: You're using a pre-release version of Spin (1.6.0-pre0). This plugin might not be compatible (supported: >=1.3). Continuing anyway.
Error: No such file or directory '/Users/mikkel/Library/Application Support/spin/plugins/cloud-gpu/fermyon-cloud-gpu/spin.toml'

Learn more at https://developer.fermyon.com/cloud/faq
```

Having installed the plugin using
```
spin plugins install -uhttps://github.com/fermyon/spin-cloud-gpu/releases/download/canary/cloud-gpu.json -y
```

And Spin Canary, using the installer script.

The folder `cloud-gpu` in the `plugins` folder doesn't exist at this point.

**Comment by itowlson** [comment]
@karthik2804 When I untar the release asset it only contains the binary and the licence.  Looks like the release action is just tarring those files rather than using the manifest shell script?  https://github.com/fermyon/spin-cloud-gpu/blob/30bbcfe59c99e1bea339cf17f4361cbf12b13cbb/.github/workflows/release.yaml#L108

**Comment by karthik2804** [comment]
Ah thanks for spotting that - I will update the release action.
